#ifndef DT_EVENT_DEF_H
#define DT_EVENT_DEF_H

enum
{
    EVENT_SERVER_INVALID = -1,
    EVENT_SERVER_MAIN = 0,
    EVENT_SERVER_PLAYER,
    EVENT_SERVER_AUDIO,
    EVENT_SERVER_VIDEO,
};

enum
{
    /*player event */
    PLAYER_EVENT_INVALID = -1,
    PLAYER_EVENT_START,
    PLAYER_EVENT_PAUSE,
    PLAYER_EVENT_RESUME,
    PLAYER_EVENT_SEEK,
    PLAYER_EVENT_STOP,

    /*audio event */
    AUDIO_EVENT_START = 100,
    AUDIO_EVENT_PAUSE,
    AUDIO_EVENT_RESUME,
    AUDIO_EVENT_MUTE,
    AUDIO_EVENT_STOP,
    AUDIO_EVENT_RELEASE,

    /*video event */
    VIDEO_EVENT_START = 200,
    VIDEO_EVENT_PAUSE,
    VIDEO_EVENT_RESUME,
    VIDEO_EVENT_STOP,
};

#endif
